name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker
        run: docker build . --tag omnipay-vindicia

      - name: Test
        run: docker run --rm omnipay-vindicia make test
